/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'guilhermeluizstolfo' at '26/08/16 15:16' with Gradle 3.0
 *
 * @author guilhermeluizstolfo, @date 26/08/16 15:16
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
